name: CICD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      #- name: Run Super-Linter
      #  uses: github/super-linter@v3
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy-app
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{secrets.SSH_HOST}}
          remote-user: ${{secrets.SSH_USERNAME}}
          private-ssh-key: ${{secrets.SSH_KEY}}
          destination-path: ~/var/www/html/